### ISSUE TITLE
how to use it ,

### ISSUE THREAD

**Issue by herbiel** [davehorton/drachtio-dialogflow-phone-gateway#3]
cd drachtio-dialogflow-phone-gateway
and node app.js
it show me 
{"level":30,"time":1590400050661,"pid":9877,"hostname":"dialogflow-fs","msg":"connected to sip on tcp/10.170.0.2:5060,udp/10.170.0.2:5060","v":1}
but how can i call by this ?

**Comment by davehorton** [comment]
This is a pretty open-ended question.  Have you read the REAMDE file and set the configuration for your dialogflow app etc?

If so, incoming calls should be connected to your dialogflow app.  That's how you "use it"

**Comment by herbiel** [comment]
> This is a pretty open-ended question. Have you read the REAMDE file and set the configuration for your dialogflow app etc?
> 
> If so, incoming calls should be connected to your dialogflow app. That's how you "use it"

I have configure it ,but i don't know how to make incoming calls for test it

**Comment by davehorton** [comment]
you would either use a sip phone / softphone to send calls to the server, or you would have a sip trunk from a VoIP carrier

**Comment by herbiel** [comment]
> you would either use a sip phone / softphone to send calls to the server, or you would have a sip trunk from a VoIP carrier

yes,but i want to know how to connect to drachtio with softphone

**Comment by davehorton** [comment]
you configure the softphone to send to the drachtio server.....if you don't know how to configure your softphone I'm not sure I can help you

**Comment by herbiel** [comment]
> you configure the softphone to send to the drachtio server.....if you don't know how to configure your softphone I'm not sure I can help you
I can configure the softphone,but i don't know how to get drachtio server sip account and the password?

**Comment by davehorton** [comment]
device registration is not part of this app -- you are welcome to add it if you want.

Most softphones can be configured to not register, and simply send INVITEs.  Do that.
