### ISSUE TITLE
Utterance/transcribe problem - audio becomes utterance 

### ISSUE THREAD

**Issue by andreabat** [davehorton/drachtio-dialogflow-phone-gateway#8]
Hello,
 Premise: I am not very experienced with neither dialogflow nor drachtio. Dratchio-server and fs are setup with docker (drachtio-freeswitch-mrf and drachtio-server). I have created a very simple dialoglow (es) .

I start a call from a sip client ( twinkle) calling the exposed docker udp port 5063 ("5063:5060/udp"), the welcome intent is detected and initial response is delivered. but , as the response in playing back, it appears as if the playback become the input for the detection of the utterances.

I believe this is happening because the behavior of the dialog is erratic and the dialogflow log seems to confirm my idea (
![image](https://user-images.githubusercontent.com/70997/111346031-1e764200-867e-11eb-9609-7b475c5386c1.png) )

I am surely missing or misconfiguring something. Can you point me on the right direction ?

BTW. Excellent work

**Comment by davehorton** [comment]
are you saying the transcriptions you are receiving from dialogflow are of the audio file that is being played?  Then I would say you have an echo problem in your setup

**Comment by andreabat** [comment]
Thanks for pointing me out in the right direction. It turns out that I had altered some fs configuration.
Excellent.
