### ISSUE TITLE
Delay between ending speech and getting a final utterance

### ISSUE THREAD

**Issue by andreabat** [davehorton/drachtio-dialogflow-phone-gateway#9]
Hi,
I have noticed a substantial delay (up to 5 seconds) between ending speech and getting an utterance as is_final.
For example if I speak "Yes", the following intent is engaged after 5 seconds.
Can this delay be modified through configuration ? Am i the only one experiencing it ( and might be missing something ) ?

**Comment by davehorton** [comment]
Good question.  I am not aware of any such configuration.  If you look at the logs, are you getting interim transcriptions back sooner during that 5 second window?

**Comment by andreabat** [comment]
yes, but I figured that it was a problem with webhooks on dialgoflow side. It appears as if a slow or non existing webhook would influence the response time ( go figure, would have thought it was async ).
have a good day.
